name: kaggle_recbio_3
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20210324.2
  - absl-py=0.15.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - alsa-lib=1.2.3
  - argon2-cffi=21.1.0
  - astunparse=1.6.3
  - async-timeout=4.0.1
  - async_generator=1.10
  - attrs=21.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bleach=4.1.0
  - blinker=1.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=4.2.4
  - certifi
  - cffi=1.15.0
  - chardet=4.0.0
  - charset-normalizer=2.0.7
  - click=8.0.3
  - colorama=0.4.4
  - cudatoolkit=11.5.0
  - cudnn=8.2.1.32
  - cycler=0.11.0
  - dataclasses=0.8
  - dbus=1.13.6
  - debugpy=1.5.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - entrypoints=0.3
  - expat=2.4.1
  - fontconfig=2.13.1
  - fonttools=4.28.1
  - freetype=2.10.4
  - frozenlist=1.2.0
  - gast=0.4.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.70.1
  - glib-tools=2.70.1
  - google-auth=2.3.3
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - grpc-cpp=1.39.1
  - grpcio=1.39.0
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - h5py=3.1.0
  - hdf5=1.10.6
  - icu=68.2
  - idna=2.10
  - importlib-metadata=4.8.2
  - importlib_resources=5.4.0
  - iniconfig=1.1.1
  - ipykernel=6.5.0
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.0.3
  - joblib=1.1.0
  - jpeg=9d
  - jsonschema=4.2.1
  - jupyter_client=7.0.6
  - jupyter_core=4.9.1
  - jupyterlab_pygments=0.1.2
  - keras=2.6.0
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.80.0
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.70.1
  - libgomp=11.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libnghttp2=1.43.0
  - libogg=1.3.4
  - libopenblas=0.3.18
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.3
  - libprotobuf=3.16.0
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.2.1
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - markdown=3.3.6
  - markupsafe=2.0.1
  - matplotlib=3.5.0
  - matplotlib-base=3.5.0
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - more-itertools=8.12.0
  - multidict=5.2.0
  - munkres=1.1.4
  - mysql-common=8.0.27
  - mysql-libs=8.0.27
  - nbclient=0.5.9
  - nbconvert=6.3.0
  - nbformat=5.1.3
  - nccl=2.11.4.1
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - notebook=6.4.6
  - nspr=4.32
  - nss=3.72
  - numpy=1.19.5
  - oauthlib=3.1.1
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - opt_einsum=3.3.0
  - packaging=21.3
  - pandas=1.3.4
  - pandoc=2.16.1
  - pandocfilters=1.5.0
  - parso=0.8.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.3.1
  - pluggy=1.0.0
  - prometheus_client=0.12.0
  - prompt-toolkit=3.0.22
  - protobuf=3.16.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - py=1.11.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pygments=2.10.0
  - pyjwt=2.3.0
  - pyparsing=3.0.6
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pytest=6.2.5
  - python=3.9.7
  - python-dateutil=2.8.2
  - python-flatbuffers=1.12
  - python_abi=3.9
  - pytz=2021.3
  - pyu2f=0.1.5
  - pyzmq=22.3.0
  - qt=5.12.9
  - re2=2021.09.01
  - readline=8.1
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - retry=0.9.2
  - rsa=4.7.2
  - scikit-learn=1.0.1
  - scipy=1.7.2
  - send2trash=1.8.0
  - setuptools=59.2.0
  - six=1.15.0
  - snappy=1.1.8
  - sqlite=3.36.0
  - tensorboard=2.7.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.0
  - tensorflow=2.6.0
  - tensorflow-base=2.6.0
  - tensorflow-estimator=2.6.0
  - termcolor=1.1.0
  - terminado=0.12.1
  - testpath=0.5.0
  - threadpoolctl=3.0.0
  - tk=8.6.11
  - toml=0.10.2
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.1
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - tzdata=2021e
  - urllib3=1.26.7
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.1
  - wheel=0.37.0
  - wrapt=1.12.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yarl=1.7.2
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - adal==1.2.7
    - azure-common==1.1.27
    - azure-core==1.20.1
    - azure-graphrbac==0.61.1
    - azure-mgmt-authorization==0.61.0
    - azure-mgmt-containerregistry==8.2.0
    - azure-mgmt-core==1.3.0
    - azure-mgmt-keyvault==9.3.0
    - azure-mgmt-resource==13.0.0
    - azure-mgmt-storage==11.2.0
    - azureml-core==1.36.0.post2
    - backports-tempfile==1.0
    - backports-weakref==1.0.post1
    - contextlib2==21.6.0
    - cryptography==3.4.8
    - docker==5.0.3
    - isodate==0.6.0
    - jeepney==0.7.1
    - jmespath==0.10.0
    - jsonpickle==2.0.0
    - msrest==0.6.21
    - msrestazure==0.6.4
    - ndg-httpsclient==0.5.1
    - pathspec==0.9.0
    - pyopenssl==20.0.1
    - secretstorage==3.3.1
    - tensorflow-addons==0.15.0
    - typeguard==2.13.2
    - websocket-client==1.2.1
