name: kaggle_recbio
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20210324.2
  - absl-py=0.14.1
  - aiohttp=3.7.4.post0
  - alsa-lib=1.2.3
  - anyio=3.3.4
  - argon2-cffi=21.1.0
  - astor=0.8.1
  - astunparse=1.6.3
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=21.2.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bleach=4.1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - c-ares=1.17.2
  - ca-certificates=2021.10.8
  - cachetools=4.2.4
  - certifi=2021.10.8
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - click=8.0.3
  - cryptography=35.0.0
  - cycler=0.10.0
  - dataclasses=0.8
  - dbus=1.13.6
  - debugpy=1.4.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - entrypoints=0.3
  - expat=2.4.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gast=0.3.3
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.68.4
  - glib-tools=2.68.4
  - google-auth=1.35.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - grpc-cpp=1.37.1
  - grpcio=1.37.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - h5py=2.10.0
  - hdf5=1.10.6
  - icu=68.1
  - idna=3.1
  - importlib-metadata=4.8.1
  - ipykernel=6.4.1
  - ipython=7.28.0
  - ipython_genutils=0.2.0
  - jbig=2.1
  - jedi=0.18.0
  - jinja2=3.0.2
  - joblib=1.1.0
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=4.1.0
  - jupyter_client=7.0.6
  - jupyter_core=4.8.1
  - jupyter_server=1.11.1
  - jupyterlab=3.2.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.8.2
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.79.1
  - libdeflate=1.8
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.68.4
  - libgomp=11.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libnghttp2=1.43.0
  - libogg=1.3.4
  - libopenblas=0.3.18
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.3
  - libprotobuf=3.15.8
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp-base=1.2.1
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - markdown=3.3.4
  - markupsafe=2.0.1
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - multidict=5.2.0
  - mysql-common=8.0.26
  - mysql-libs=8.0.26
  - nbclassic=0.3.2
  - nbclient=0.5.4
  - nbconvert=6.2.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - notebook=6.4.4
  - nspr=4.30
  - nss=3.69
  - numpy=1.21.2
  - oauthlib=3.1.1
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - opt_einsum=3.3.0
  - packaging=21.0
  - pandas=1.3.4
  - pandoc=2.14.2
  - pandocfilters=1.5.0
  - parso=0.8.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.3.2
  - pip=21.3
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.20
  - protobuf=3.15.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pygments=2.10.0
  - pyjwt=2.3.0
  - pyopenssl=21.0.0
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python-flatbuffers=1.12
  - python_abi=3.9
  - pytz=2021.3
  - pyu2f=0.1.5
  - pyzmq=22.3.0
  - qt=5.12.9
  - re2=2021.08.01
  - readline=8.1
  - requests=2.26.0
  - requests-oauthlib=1.3.0
  - requests-unixsocket=0.2.0
  - rsa=4.7.2
  - scikit-learn=1.0
  - scipy=1.7.1
  - send2trash=1.8.0
  - setuptools=58.2.0
  - six=1.15.0
  - snappy=1.1.8
  - sniffio=1.2.0
  - sqlite=3.36.0
  - tensorboard=2.4.1
  - tensorboard-plugin-wit=1.8.0
  - tensorflow=2.4.3
  - tensorflow-base=2.4.3
  - tensorflow-estimator=2.4.0
  - termcolor=1.1.0
  - terminado=0.12.1
  - testpath=0.5.0
  - threadpoolctl=3.0.0
  - tk=8.6.11
  - tornado=6.1
  - traitlets=5.1.0
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - tzdata=2021d
  - urllib3=1.26.7
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.57.0
  - werkzeug=2.0.1
  - wheel=0.37.0
  - wrapt=1.13.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yarl=1.7.0
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.5.0
